(cl:defpackage leo_msgs-srv
  (:use )
  (:export
   "SETIMUCALIBRATION"
   "<SETIMUCALIBRATION-REQUEST>"
   "SETIMUCALIBRATION-REQUEST"
   "<SETIMUCALIBRATION-RESPONSE>"
   "SETIMUCALIBRATION-RESPONSE"
  ))

