// Generated by gencpp from file leo_msgs/SetImuCalibration.msg
// DO NOT EDIT!


#ifndef LEO_MSGS_MESSAGE_SETIMUCALIBRATION_H
#define LEO_MSGS_MESSAGE_SETIMUCALIBRATION_H

#include <ros/service_traits.h>


#include <leo_msgs/SetImuCalibrationRequest.h>
#include <leo_msgs/SetImuCalibrationResponse.h>


namespace leo_msgs
{

struct SetImuCalibration
{

typedef SetImuCalibrationRequest Request;
typedef SetImuCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetImuCalibration
} // namespace leo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::leo_msgs::SetImuCalibration > {
  static const char* value()
  {
    return "bee7d47c032e7e006759478ee568747d";
  }

  static const char* value(const ::leo_msgs::SetImuCalibration&) { return value(); }
};

template<>
struct DataType< ::leo_msgs::SetImuCalibration > {
  static const char* value()
  {
    return "leo_msgs/SetImuCalibration";
  }

  static const char* value(const ::leo_msgs::SetImuCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::leo_msgs::SetImuCalibrationRequest> should match
// service_traits::MD5Sum< ::leo_msgs::SetImuCalibration >
template<>
struct MD5Sum< ::leo_msgs::SetImuCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::leo_msgs::SetImuCalibration >::value();
  }
  static const char* value(const ::leo_msgs::SetImuCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::leo_msgs::SetImuCalibrationRequest> should match
// service_traits::DataType< ::leo_msgs::SetImuCalibration >
template<>
struct DataType< ::leo_msgs::SetImuCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::leo_msgs::SetImuCalibration >::value();
  }
  static const char* value(const ::leo_msgs::SetImuCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::leo_msgs::SetImuCalibrationResponse> should match
// service_traits::MD5Sum< ::leo_msgs::SetImuCalibration >
template<>
struct MD5Sum< ::leo_msgs::SetImuCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::leo_msgs::SetImuCalibration >::value();
  }
  static const char* value(const ::leo_msgs::SetImuCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::leo_msgs::SetImuCalibrationResponse> should match
// service_traits::DataType< ::leo_msgs::SetImuCalibration >
template<>
struct DataType< ::leo_msgs::SetImuCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::leo_msgs::SetImuCalibration >::value();
  }
  static const char* value(const ::leo_msgs::SetImuCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEO_MSGS_MESSAGE_SETIMUCALIBRATION_H
