// Generated by gencpp from file leo_msgs/SetImuCalibrationResponse.msg
// DO NOT EDIT!


#ifndef LEO_MSGS_MESSAGE_SETIMUCALIBRATIONRESPONSE_H
#define LEO_MSGS_MESSAGE_SETIMUCALIBRATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leo_msgs
{
template <class ContainerAllocator>
struct SetImuCalibrationResponse_
{
  typedef SetImuCalibrationResponse_<ContainerAllocator> Type;

  SetImuCalibrationResponse_()
    : success(false)  {
    }
  SetImuCalibrationResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetImuCalibrationResponse_

typedef ::leo_msgs::SetImuCalibrationResponse_<std::allocator<void> > SetImuCalibrationResponse;

typedef boost::shared_ptr< ::leo_msgs::SetImuCalibrationResponse > SetImuCalibrationResponsePtr;
typedef boost::shared_ptr< ::leo_msgs::SetImuCalibrationResponse const> SetImuCalibrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator1> & lhs, const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator1> & lhs, const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leo_msgs/SetImuCalibrationResponse";
  }

  static const char* value(const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetImuCalibrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leo_msgs::SetImuCalibrationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEO_MSGS_MESSAGE_SETIMUCALIBRATIONRESPONSE_H
